# User config
author: "Ariana"
tagline: "Pineapple Certfied Jekyll Theme - ariana"
description: "I want pineapple pizza. Pineapple on pizza soon followed..."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "pineapple@example.com"
linkedin: 
twitter: 
github: 

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed